import Head from "next/head";
import { useState } from "react";
import Grid from "@mui/material/Grid";
import RssInputForm from "../components/RSSInputForm";
import styles from "../styles/home.module.css";
import getFeed, { RssElementData } from "../lib/rssHelpers";
import RssFeedItemsDisplay from "../components/RssFeedItemsDisplay";
export default function Home() {
  const [currentData, setCurrentData] = useState<RssElementData[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const getRssFeedData = async (formValue: string) => {
    let results: RssElementData[] = [];
    setIsLoading(true);

    await getFeed(formValue).then((data) => {
      let res = { ...data };
      Object.values(res).forEach((result) => {
        results.push(result);
      });
      setCurrentData(results);
      setIsLoading(false);
    });
  };
  return (
    <>
      <Head>
        <title>Rss Reader Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <h2>RSS Reader</h2>

      <Grid container spacing={2} sx={{ ...styles }}>
        <Grid item xs={6} md={12}></Grid>
        <Grid item xs={12} md={12}>
          <RssInputForm
            textInputLabel="Enter RSS URL"
            handleSubmit={getRssFeedData}
          />
        </Grid>
        <Grid item>
          {isLoading ? (
            <p>Loading</p>
          ) : (
            <RssFeedItemsDisplay currentData={currentData} />
          )}
        </Grid>
      </Grid>
    </>
  );
}
